version: '3'

services:
  app:
    build: cephs-citchen
    ports: 
      - '3000:3000'

  shoppinglist:
    image: fallensteed/cephs-shoppinglist
    depends_on:
      - 'database'
    ports: 
      - '3001:3000'

  shoppinglistapi:
    image: fallensteed/cephs-shoppinglist-api
    restart: always
    depends_on:
      - 'database'
    ports:
      - '4001:4001'

  pantrylist:
    image: btanusi/cephs-pantrylist
    restart: always
    depends_on:
      - 'database'
    ports:
      - '3002:3000'

  pantrylistapi:
    image: btanusi/cephs-pantrylist-api
    restart: always
    depends_on:
      - 'database'
    ports:
      - '8000:8000'

  recipes:
    image: azteckind/cephs-recipe-app
    restart: always
    depends_on:
      - 'database'
    ports:
      - '3003:3000'

  units:
    image: ananaso/cephs-unitconverter-app
    restart: always
    depends_on:
      - 'database'
    ports:
      - '3004:3000'

  unitsapi:
    image: ananaso/cephs-unitconverter-api
    restart: always
    depends_on:
      - 'database'
    ports:
      - '3333:3333'

  database:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=cephs_citchen
      - POSTGRES_USER=ceph
      - POSTGRES_PASSWORD=ceph
    volumes:
      - ./01_items.sql:/docker-entrypoint-initdb.d/01_items.sql
      - ./02_shoppinglist.sql:/docker-entrypoint-initdb.d/02_shoppinglist.sql
      - ./03_pantrylist.sql:/docker-entrypoint-initdb.d/03_pantrylist.sql
      - ./04_recipe.sql:/docker-entrypoint-initdb.d/04_recipe.sql
      - ./05_units.sql:/docker-entrypoint-initdb.d/05_units.sql